name: Build & Test

on: [push]

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3

    - name: Setup Visual Studio Development Environment
      uses: compnerd/gha-setup-vsdevenv@main

    - name: Install Swift
      uses: compnerd/gha-setup-swift@main
      with:
        branch: swift-5.8-release
        tag: 5.8-RELEASE

    - name: Build
      shell: pwsh
      run: swift build --verbose --build-tests

    - name: Test
      shell: pwsh
      run: swift test --verbose --skip-build